name: MTK_SDK 21.02 for bpi-r4 and release

on:
  workflow_dispatch:

env:
  REMOTE_REPOSITORY: openwrt/openwrt
  REMOTE_BRANCH: openwrt-21.02
  CONFIG_FILE: mtk-sdk-2102.config
  CUSTOM_FILES_PATH: files/
  RELEASE_PREFIX: Mediatek_SDK_2102

jobs:
  build:
    name: Build OpenWrt
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang flex bison g++ gawk gcc-multilib \
            g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget
      - name: Checkout remote repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: "custom_repo"
      - name: Update and install feeds
        run: |
          echo "src-git mtk_openwrt_feed https://git01.mediatek.com/openwrt/feeds/mtk-openwrt-feeds" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Apply MediaTek OpenWrt files and patches
        shell: bash {0}
        run: |
          cp -af ./feeds/mtk_openwrt_feed/21.02/files/* .
          cp -af ./feeds/mtk_openwrt_feed/tools .
          for file in $(find ./feeds/mtk_openwrt_feed/21.02/patches-base -name "*.patch" | sort); do patch -f -p1 -i ${file}; done
          for file in $(find ./feeds/mtk_openwrt_feed/21.02/patches-feeds -name "*.patch" | sort); do patch -f -p1 -i ${file}; done
      - name: Configure firmware image
        run: |
          mv custom_repo/${{ env.CONFIG_FILE }} .config
          make defconfig -j$(nproc)
      - name: Build the firmware image
        run: make download world V=s -j$(nproc)
      - name: Package output
        run: tar -cvf mtk_bpi_r4-images.tar bin/targets/mediatek/mt7988
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mtk_bpi_r4-images
          path: mtk_bpi_r4-images.tar

  release:
    name: Create release
    needs: [build]
    if: needs.build.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: mtk_bpi_r4-images
      - name: Extract artifacts
        run: tar xf mtk_bpi_r4-images.tar
      - name: Get current date
        run: echo "RELEASE_DATE=$(date +%F)" >> $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          files: bin/targets/mediatek/mt7988/*
          tag_name: ${{ env.RELEASE_PREFIX }}-${{ env.RELEASE_DATE }}
          name: MTK_SDK_21.02 BPI-r4 ${{ env.RELEASE_DATE }}
          body: |
            Updated prebuilt images for ${{ env.RELEASE_DATE }}
            Build Commit: ${{ needs.check_commits.outputs.latest_commit_sha }}
      - name: Clean up old releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
